<?php

function cipher_menu() {
  $items['cipher'] = array(
     'title' => 'Shift Cipher',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('cipher_form'),
     'access callback' => TRUE,
     'type' => MENU_NORMAL_ITEM,
  );
  $items['cipher'] = array(
     'title' => 'Shift Cipher',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('cipher_form'),
     'access callback' => TRUE,
     'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
