<?php

function cipher_menu() {
  $items['cipher'] = array(
     'title' => 'Shift Cipher',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('cipher_form'),
     'access callback' => TRUE,
     'type' => MENU_NORMAL_ITEM,
  );
  $items['cipher_results'] = array(
     'title' => 'Results',
     'page callback' => 'cipher_results',
     'access callback' => TRUE,
     'type' => MENU_CALLBACK,
  );
  return $items;
}

function cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift Value',
    '#type' => 'textfield',
    '#description' => t('Enter a positive number of spaces to shift the letters of the cipher.'),
    '#element_validate' => array('element_validate_integer_positive'),
    '#required' => TRUE,
  );
  $form['shift_direction'] = array(
    '#title' => 'Shift Direction',
    '#type' => 'textfield',
    '#description' => t('Enter "left" or "right" to choose a shift direction.'),
    '#element_validate' => array('element_validate_direction'),
    '#required' => TRUE,
  );
  $form['shift_phrase'] = array(
    '#title' => 'Shift Phrase',
    '#type' => 'textfield',
    '#description' => t('Enter the word or phrase to be shifted'),
    '#element_validate' => array('element_validate_phrase'),
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Go',
  );
}
